#!/bin/bash

ANDROID_BUILD_TOP="$(dirname $(realpath "$0"))"
CHECK="$(echo $1 | grep -q check && echo 1)"
GERRIT_USERNAME="$(git config review.review.lineageos.org.username)"

function repopick() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "${@: -1} - " ; ssh lineage-gerrit gerrit query ${@: -1} --format=JSON | jq --slurp -r '.[0].status'
    else
        ${ANDROID_BUILD_TOP}/lineage/scripts/repopick/repopick.py \
            -g "ssh://$GERRIT_USERNAME@review.lineageos.org:29418" $@ &
    fi
}

function repopickchain() {
    if [[ "$CHECK" = "1" ]]; then
        echo -n "$1 - " ; ssh lineage-gerrit gerrit query $1 --format=JSON | jq --slurp -r '.[0].status'
    else
        `${ANDROID_BUILD_TOP}/gen_chain $@`
    fi
}

function rc() {
    echo `${ANDROID_BUILD_TOP}/gen_chain $@ | cut -b10-`
}

#
# _examples_
#
# # repo/1
# changes=(
#     2137 # hello
#     `rc 2137` # hello (chain)
# )
# repopick ${changes[@]}
#
# # repo/2
# repopickchain 2137 # hello (chain)
#
# # repo/3
# repopick 2137 # hello
#

# device/lineage/sepolicy
repopickchain 431717 # common: Label ro.lineage.device prop

# device/qcom/sepolicy_vndr/legacy-um
repopickchain 469528 # BACKPORT: sepolicy_vndr: Provide net_admin capability for lowi-server

# frameworks/base
repopickchain 475400 # SystemUI: Fix loading of brightness icons on moving slider
repopickchain 474452 # Support select and l1/r1 to control brightness

# hardware/interfaces
repopickchain 469436 # Health: Indicate missing battery properties with -1

# hardware/qcom-caf/common
repopickchain 477487 # libqti-perfd-client: Reset Power HAL on binder death

# hardware/qcom-caf/sm8350/display
repopickchain 474977 # sdm: Operate FINGERPRINT_MASK for oplus optical UDFPS

# lineage-sdk
repopickchain 474451 # lineage-sdk: Add setting for atv brightness buttons

# packages/apps/Settings
repopickchain 474721 # Settings: Fix custom Private DNS hostname being overwritten

# packages/apps/TvSettings
repopickchain 474450 # TvSettings: Support brightness button combo

# packages/apps/WallpaperPicker2
repopickchain 471202 # Update settings repository to latest interface

# packages/modules/Permission
repopickchain 474328 # PermissionController: Add missing permission groups

# vendor/lineage
repopickchain 477314 # overlay: Update DocumentsUIOverlay

wait
